# Copyright 2024 calm.wang@hotmail.com
# SPDX-License-Identifier: LGPL-3.0-only
version: '3.9'

networks:
  tg_bot_network:

services:
  tg_bot:
    image: calmw/tbot:0.0.69
    container_name: tg_bot
    restart: always
    environment:
      - RPC_BSC=x
      - RPC_MATCH=x
      - RPC_MATCH_L2=x
      - TG_TOKEN=x
      - CHAT_ID=x
      - CHAT_ID_DEBUG_GROUP=x
      - BRIDGE_IP=x
      - PRIVATE_KEY=x
      - REPORT_INTERVAL=x
    #      - REPORT_INTERVAL=65
    #      - CHAT_ID=4529125714
    networks:
      - tg_bot_network
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G