# Copyright 2024 calm.wang@hotmail.com
# SPDX-License-Identifier: LGPL-3.0-only
version: '3.9'

networks:
  tg_bot_network:

services:
  tg_bot:
    #    image: calmw/tbot:0.0.12 # arm64
    image: calmw/tbot:0.0.13 # x86
    container_name: tg_bot
    restart: always
    environment:
      - RPC=xxx
      - TG_TOKEN=xxx
      - ChatId=xxx
      - BalanceThreshold=20000000000000000
      #      - BalanceThreshold=2000000000000000000
      #      - Report_Interval=20
      - Report_Interval=1800
    networks:
      - tg_bot_network
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G