# Copyright 2024 calm.wang@hotmail.com
# SPDX-License-Identifier: LGPL-3.0-only
version: '3.9'

networks:
  tg_bot_network:

services:
  tg_bot:
    image: calmw/tbot:0.0.53
    container_name: tg_bot
    restart: always
    environment:
      - RPC_BSC=xx
      - RPC_MATCH=xx
      - RPC_MATCH_L2=xx
      - TG_TOKEN=xx
      - CHAT_ID=xx
      - CHAT_ID_DEBUG_GROUP=xx
      - BRIDGE_IP=172.28.0.1
      - PRIVATE_KEY=xx
      - REPORT_INTERVAL=1800
    #      - REPORT_INTERVAL=65
    #      - CHAT_ID=4529125714
    networks:
      - tg_bot_network
    logging:
      driver: "json-file"
      options:
        max-size: "5m"
        max-file: "1"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G